"""Initial migration

Revision ID: 08daff9f9e2a
Revises: 
Create Date: 2025-07-10 08:06:30.075470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08daff9f9e2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'installation_info', ['guid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'installation_info', type_='unique')
    # ### end Alembic commands ###
