"""add_tracking_duration_to_triggers

Revision ID: d1fe7ad7ecfa
Revises: 321a0601fef9
Create Date: 2025-12-13 18:08:01.355600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1fe7ad7ecfa'
down_revision = '321a0601fef9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'start_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Recording start time (for camera videos)',
               existing_nullable=True)
    op.alter_column('media', 'end_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Recording end time (for camera videos)',
               existing_nullable=True)
    op.drop_index('idx_media_end_timestamp', table_name='media')
    op.drop_index('idx_media_start_timestamp', table_name='media')
    op.drop_index('idx_media_collections_camera_device_id', table_name='media_collections')
    op.create_index(op.f('ix_media_collections_camera_device_id'), 'media_collections', ['camera_device_id'], unique=False)
    op.add_column('triggers', sa.Column('tracking_duration', sa.String(length=50), nullable=False, server_default='10 minutes', comment='Time window for MVR search (e.g., "5 seconds", "10 minutes", "2 hours", "1 day")'))
    op.alter_column('triggers', 'age_range_operator',
               existing_type=sa.VARCHAR(length=50),
               comment='Age comparison operator (optional filter)',
               existing_nullable=True)
    op.alter_column('triggers', 'age_range_value',
               existing_type=sa.VARCHAR(length=50),
               comment="Age threshold value (e.g., '18', '65', '18-30' for BETWEEN)",
               existing_nullable=True)
    op.alter_column('triggers', 'gender_filter',
               existing_type=sa.VARCHAR(length=50),
               comment='Gender filter (male, female, any)',
               existing_comment="Gender filter (e.g., 'Any', '3M/2W', 'Male', 'Female')",
               existing_nullable=True)
    op.alter_column('triggers', 'camera_device_id',
               existing_type=sa.VARCHAR(length=255),
               comment="Device ID of the camera from Camera service (e.g., 'usb_camera_0', 'rtsp_192.168.1.76_554')",
               existing_comment="Device ID of the camera (e.g., 'usb_camera_0')",
               existing_nullable=False)
    op.alter_column('triggers', 'camera_name',
               existing_type=sa.VARCHAR(length=255),
               comment="Friendly name of the camera (e.g., 'Front Door', 'Main Entrance')",
               existing_comment="Friendly name of the media source (e.g., 'Camera 01, 03')",
               existing_nullable=True)
    op.alter_column('triggers', 'action',
               existing_type=sa.VARCHAR(length=50),
               comment='Action to execute when conditions are met (deprecated - use action_uuid)',
               existing_comment='Action to execute when conditions are met',
               existing_nullable=False)
    op.alter_column('triggers', 'action_uuid',
               existing_type=sa.UUID(),
               comment='UUID of the linked user action',
               existing_nullable=True)
    op.alter_column('triggers', 'enable_demographic_conditions',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Enable demographic-based trigger evaluation (percent_male, percent_female, etc.)',
               existing_nullable=False)
    op.alter_column('triggers', 'signage_device_ids',
               existing_type=sa.TEXT(),
               comment='JSON array of signage device UUIDs: ["device-uuid-1", "device-uuid-2"]',
               existing_comment='JSON array of signage device UUIDs for playback control: ["device-uuid-1", "device-uuid-2"]',
               existing_nullable=True)
    op.alter_column('triggers', 'signage_transition_mode',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_comment='Playlist transition mode: immediate | after_current | fade',
               existing_nullable=False)
    op.alter_column('triggers', 'signage_fade_duration_ms',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='Fade duration in milliseconds for fade transition mode',
               existing_nullable=False)
    op.alter_column('triggers', 'cooldown_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='Minimum seconds between trigger firings to prevent spam',
               existing_nullable=False)
    op.drop_index('idx_trigger_action_uuid', table_name='triggers')
    op.drop_index('idx_trigger_cooldown', table_name='triggers')
    op.drop_index('idx_trigger_demographic_enabled', table_name='triggers')
    op.drop_index('idx_trigger_tracking_number', table_name='triggers')
    op.drop_index('idx_trigger_tracking_unit', table_name='triggers')
    op.create_index(op.f('ix_triggers_action_uuid'), 'triggers', ['action_uuid'], unique=False)
    op.create_index(op.f('ix_triggers_enable_demographic_conditions'), 'triggers', ['enable_demographic_conditions'], unique=False)
    op.create_index(op.f('ix_triggers_last_fired_at'), 'triggers', ['last_fired_at'], unique=False)
    op.create_index(op.f('ix_triggers_tracking_duration'), 'triggers', ['tracking_duration'], unique=False)
    op.drop_column('triggers', 'tracking_number')
    op.drop_column('triggers', 'tracking_unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('triggers', sa.Column('tracking_unit', sa.VARCHAR(length=20), server_default=sa.text("'minutes'::character varying"), autoincrement=False, nullable=False, comment='Unit for tracking duration (seconds, minutes, hours, days, months)'))
    op.add_column('triggers', sa.Column('tracking_number', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False, comment='Number value for tracking duration'))
    op.drop_index(op.f('ix_triggers_tracking_duration'), table_name='triggers')
    op.drop_index(op.f('ix_triggers_last_fired_at'), table_name='triggers')
    op.drop_index(op.f('ix_triggers_enable_demographic_conditions'), table_name='triggers')
    op.drop_index(op.f('ix_triggers_action_uuid'), table_name='triggers')
    op.create_index('idx_trigger_tracking_unit', 'triggers', ['tracking_unit'], unique=False)
    op.create_index('idx_trigger_tracking_number', 'triggers', ['tracking_number'], unique=False)
    op.create_index('idx_trigger_demographic_enabled', 'triggers', ['enable_demographic_conditions'], unique=False)
    op.create_index('idx_trigger_cooldown', 'triggers', ['last_fired_at'], unique=False)
    op.create_index('idx_trigger_action_uuid', 'triggers', ['action_uuid'], unique=False)
    op.alter_column('triggers', 'cooldown_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('60'),
               existing_comment='Minimum seconds between trigger firings to prevent spam',
               existing_nullable=False)
    op.alter_column('triggers', 'signage_fade_duration_ms',
               existing_type=sa.INTEGER(),
               server_default=sa.text('2000'),
               existing_comment='Fade duration in milliseconds for fade transition mode',
               existing_nullable=False)
    op.alter_column('triggers', 'signage_transition_mode',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'immediate'::character varying"),
               existing_comment='Playlist transition mode: immediate | after_current | fade',
               existing_nullable=False)
    op.alter_column('triggers', 'signage_device_ids',
               existing_type=sa.TEXT(),
               comment='JSON array of signage device UUIDs for playback control: ["device-uuid-1", "device-uuid-2"]',
               existing_comment='JSON array of signage device UUIDs: ["device-uuid-1", "device-uuid-2"]',
               existing_nullable=True)
    op.alter_column('triggers', 'enable_demographic_conditions',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='Enable demographic-based trigger evaluation (percent_male, percent_female, etc.)',
               existing_nullable=False)
    op.alter_column('triggers', 'action_uuid',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID of the linked user action',
               existing_nullable=True)
    op.alter_column('triggers', 'action',
               existing_type=sa.VARCHAR(length=50),
               comment='Action to execute when conditions are met',
               existing_comment='Action to execute when conditions are met (deprecated - use action_uuid)',
               existing_nullable=False)
    op.alter_column('triggers', 'camera_name',
               existing_type=sa.VARCHAR(length=255),
               comment="Friendly name of the media source (e.g., 'Camera 01, 03')",
               existing_comment="Friendly name of the camera (e.g., 'Front Door', 'Main Entrance')",
               existing_nullable=True)
    op.alter_column('triggers', 'camera_device_id',
               existing_type=sa.VARCHAR(length=255),
               comment="Device ID of the camera (e.g., 'usb_camera_0')",
               existing_comment="Device ID of the camera from Camera service (e.g., 'usb_camera_0', 'rtsp_192.168.1.76_554')",
               existing_nullable=False)
    op.alter_column('triggers', 'gender_filter',
               existing_type=sa.VARCHAR(length=50),
               comment="Gender filter (e.g., 'Any', '3M/2W', 'Male', 'Female')",
               existing_comment='Gender filter (male, female, any)',
               existing_nullable=True)
    op.alter_column('triggers', 'age_range_value',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Age threshold value (e.g., '18', '65', '18-30' for BETWEEN)",
               existing_nullable=True)
    op.alter_column('triggers', 'age_range_operator',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Age comparison operator (optional filter)',
               existing_nullable=True)
    op.drop_column('triggers', 'tracking_duration')
    op.drop_index(op.f('ix_media_collections_camera_device_id'), table_name='media_collections')
    op.create_index('idx_media_collections_camera_device_id', 'media_collections', ['camera_device_id'], unique=False)
    op.create_index('idx_media_start_timestamp', 'media', ['start_timestamp'], unique=False)
    op.create_index('idx_media_end_timestamp', 'media', ['end_timestamp'], unique=False)
    op.alter_column('media', 'end_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Recording end time (for camera videos)',
               existing_nullable=True)
    op.alter_column('media', 'start_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Recording start time (for camera videos)',
               existing_nullable=True)
    # ### end Alembic commands ###
