#!/usr/bin/env bash
# Sync repo SQL migrations into the Windows/Lima installer schema pack.
# Run from a machine that has the full monorepo (CI / release / Lima host).
#
#   bash deployment/mac-lima/sync-schema-pack.sh
#
# Output: deployment/windows-installer/schema/pack/*.sql (+ MANIFEST)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PACK_DIR="$REPO_ROOT/deployment/windows-installer/schema/pack"
COMPAT="$REPO_ROOT/deployment/mac-lima/sql"

rm -rf "$PACK_DIR"
mkdir -p "$PACK_DIR"

n=0
add() {
  local src="$1"
  local base
  base="$(basename "$src")"
  if [[ ! -f "$src" ]]; then
    echo "WARN: missing $src" >&2
    return 0
  fi
  n=$((n + 1))
  local dest
  dest="$(printf '%03d_%s' "$n" "$base")"
  cp -f "$src" "$PACK_DIR/$dest"
  echo "$dest  <=  ${src#"$REPO_ROOT/"}" | tee -a "$PACK_DIR/MANIFEST.txt"
}

: > "$PACK_DIR/MANIFEST.txt"
echo "# Generated by sync-schema-pack.sh — do not edit by hand" >> "$PACK_DIR/MANIFEST.txt"
echo "# $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$PACK_DIR/MANIFEST.txt"
echo >> "$PACK_DIR/MANIFEST.txt"

# --- Vision ---
VIS="$REPO_ROOT/ppl-meta-vision/migrations"
add "$VIS/001_session_based_face_detection_schema.sql"
add "$VIS/002_add_frame_dimensions_to_face_detections.sql"
add "$VIS/003_add_mv_model_provenance.sql"
add "$VIS/004_add_object_detections.sql"
add "$VIS/005_object_detections_keypoints.sql"
add "$VIS/add_representative_faces_and_route_data.sql"

# --- VMeta MVR first ---
VMETA="$REPO_ROOT/ppl-meta-vmeta/migrations"
add "$VMETA/002_mvr_people_schema.sql"
add "$VMETA/003_add_unique_mvr_count.sql"

# --- VMeta cross-video core ---
VMETA_DB="$REPO_ROOT/ppl-meta-vmeta/src/database/migrations"
add "$VMETA_DB/002_cross_video_tracking_schema.sql"
add "$VMETA_DB/003_cross_video_tracking_indexes_final.sql"
add "$VMETA_DB/003_mvr_hierarchy.sql"
add "$VMETA_DB/004_single_media_mvr_columns.sql"
add "$VMETA_DB/005_make_featured_individual_nullable_for_isolated.sql"
add "$VMETA_DB/006_add_demographics_to_individuals.sql"
add "$VMETA_DB/007_mvr_search_sessions.sql"
add "$VMETA_DB/008_people_counters_batches.sql"
add "$VMETA_DB/009_mvr_search_session_people.sql"

# --- VMeta features ---
add "$VMETA/004_add_embedding_cache.sql"
add "$VMETA/005_add_mvr_embeddings.sql"
add "$VMETA/006_batch_processing_state.sql"
add "$VMETA/006_add_video_uuids_optimization.sql"
add "$VMETA/007_batch_video_assignments.sql"
add "$VMETA/008_batch_processing_history.sql"
add "$VMETA/009_batch_processing_config.sql"
add "$VMETA/010_partial_batch_support.sql"
add "$VMETA/011_individual_groups_schema.sql"
add "$VMETA/012_individual_thumbnails.sql"
add "$VMETA/018_add_mvr_people_names.sql"
add "$VMETA/019_instant_detection_storage.sql"
add "$VMETA/020_add_identity_group_uuid.sql"
add "$VMETA/021_add_unmerged_action_to_audit_log.sql"
add "$VMETA/022_mvr_people_body.sql"
add "$VMETA/add_individual_caching_support.sql"

# --- Cameras (skip rollbacks / #comment SQL) ---
CAM="$REPO_ROOT/ppl-meta-cameras/migrations"
add "$CAM/001_add_hardware_identifier.sql"
add "$CAM/002_create_pending_settings_table.sql"
add "$CAM/003_add_hybrid_settings_support.sql"
add "$CAM/add_camera_archive.sql"
add "$CAM/add_instant_detection_storage_settings.sql"
add "$CAM/add_pipeline_settings.sql"
add "$CAM/add_tolerance_percent.sql"
add "$CAM/add_workflow_settings.sql"
add "$CAM/create_profile_templates.sql"
add "$CAM/increase_model_serial_number_sizes.sql"

# --- Media ---
add "$REPO_ROOT/ppl-meta-media/migrations/add_recording_timestamps.sql"

# --- Installer ORM clash fixes only ---
add "$COMPAT/012_recording_sessions_cameras_compat.sql"
add "$COMPAT/014_camera_settings_and_enable_detection.sql"

# --- Pack-only installer DDL (fixed names; must survive sync wipe) ---
# These are not auto-numbered; apply.sh sorts lexicographically after 046.
for pack_only in \
  047_orchestrator_workflow_settings.sql \
  048_individuals_created_by_session.sql
do
  src="$COMPAT/$pack_only"
  if [[ -f "$src" ]]; then
    cp -f "$src" "$PACK_DIR/$pack_only"
    echo "$pack_only  <=  ${src#"$REPO_ROOT/"}" | tee -a "$PACK_DIR/MANIFEST.txt"
  else
    echo "WARN: missing pack-only $src" >&2
  fi
done

# Preflight SQL baked into pack
cat > "$PACK_DIR/000_preflight_extensions_and_stub_reconcile.sql" <<'SQL'
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS vector;

DO $$
DECLARE
  emb_udt TEXT;
  has_gender_est BOOLEAN;
  has_gender BOOLEAN;
BEGIN
  SELECT c.udt_name INTO emb_udt
  FROM information_schema.columns c
  WHERE c.table_schema = 'public'
    AND c.table_name = 'mvr_people'
    AND c.column_name = 'face_embedding';

  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='mvr_people' AND column_name='gender_estimate'
  ) INTO has_gender_est;

  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='mvr_people' AND column_name='gender'
  ) INTO has_gender;

  IF emb_udt IS NOT NULL AND emb_udt <> 'vector' THEN
    RAISE NOTICE 'Dropping stub mvr_people (face_embedding udt=%)', emb_udt;
    DROP TABLE IF EXISTS individual_mvr_mapping CASCADE;
    DROP TABLE IF EXISTS mvr_people CASCADE;
  ELSIF has_gender_est AND NOT has_gender THEN
    RAISE NOTICE 'Dropping stub mvr_people (gender_estimate without gender)';
    DROP TABLE IF EXISTS individual_mvr_mapping CASCADE;
    DROP TABLE IF EXISTS mvr_people CASCADE;
  END IF;
END $$;
SQL

# Ensure 000 sorts first — already named 000_
echo
echo "Synced $n migration files (+ 000 preflight) -> $PACK_DIR"
wc -l "$PACK_DIR/MANIFEST.txt" | awk '{print "MANIFEST lines:", $1}'

# Bundle for Windows installer download (single artifact)
SCHEMA_DIR="$(dirname "$PACK_DIR")"
(
  cd "$SCHEMA_DIR"
  tar -czf pack.tar.gz -C pack .
)
cp -f "$REPO_ROOT/deployment/mac-lima/verify-codebase-schema.sh" "$SCHEMA_DIR/verify.sh"
cp -f "$REPO_ROOT/deployment/windows-installer/schema/apply.sh" "$SCHEMA_DIR/apply.sh" 2>/dev/null || true
echo "Wrote $SCHEMA_DIR/pack.tar.gz ($(du -h "$SCHEMA_DIR/pack.tar.gz" | awk '{print $1}'))"