// Mocks generated by Mockito 5.4.6 from annotations
// in signage_simple_player/test/integration/full_workflow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:signage_simple_player/api/signage_api_client.dart' as _i3;
import 'package:signage_simple_player/models/playback_history.dart' as _i7;
import 'package:signage_simple_player/models/playback_models.dart' as _i2;
import 'package:signage_simple_player/models/video_list.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePlaybackStatus_0 extends _i1.SmartFake
    implements _i2.PlaybackStatus {
  _FakePlaybackStatus_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SignageApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignageApiClient extends _i1.Mock implements _i3.SignageApiClient {
  MockSignageApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  String get deviceId =>
      (super.noSuchMethod(
            Invocation.getter(#deviceId),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#deviceId),
            ),
          )
          as String);

  @override
  _i5.Future<_i6.VideoList?> syncPlaylist({int? lastSyncVersion}) =>
      (super.noSuchMethod(
            Invocation.method(#syncPlaylist, [], {
              #lastSyncVersion: lastSyncVersion,
            }),
            returnValue: _i5.Future<_i6.VideoList?>.value(),
          )
          as _i5.Future<_i6.VideoList?>);

  @override
  _i5.Future<_i2.PlaybackStatus> sendControlCommand({
    required String? command,
    Map<String, dynamic>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendControlCommand, [], {
              #command: command,
              #parameters: parameters,
            }),
            returnValue: _i5.Future<_i2.PlaybackStatus>.value(
              _FakePlaybackStatus_0(
                this,
                Invocation.method(#sendControlCommand, [], {
                  #command: command,
                  #parameters: parameters,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.PlaybackStatus>);

  @override
  _i5.Future<void> reportStatus({required _i2.PlaybackStatus? currentState}) =>
      (super.noSuchMethod(
            Invocation.method(#reportStatus, [], {#currentState: currentState}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> uploadHistory({
    required List<_i7.PlaybackHistoryEntry>? entries,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadHistory, [], {#entries: entries}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<Map<String, dynamic>> getServerInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getServerInfo, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> getVideoMetadata({
    required String? videoId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getVideoMetadata, [], {#videoId: videoId}),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> reportError({
    required String? errorType,
    required String? errorMessage,
    String? videoId,
    String? playlistId,
    Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reportError, [], {
              #errorType: errorType,
              #errorMessage: errorMessage,
              #videoId: videoId,
              #playlistId: playlistId,
              #context: context,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
