// Mocks generated by Mockito 5.4.6 from annotations
// in signage_simple_player/test/services/sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:signage_simple_player/api/signage_api_client.dart' as _i5;
import 'package:signage_simple_player/database/playlist_database.dart' as _i9;
import 'package:signage_simple_player/models/playback_history.dart' as _i4;
import 'package:signage_simple_player/models/playback_models.dart' as _i2;
import 'package:signage_simple_player/models/video_list.dart' as _i8;
import 'package:sqflite/sqflite.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePlaybackStatus_0 extends _i1.SmartFake
    implements _i2.PlaybackStatus {
  _FakePlaybackStatus_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabase_1 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaybackSummary_2 extends _i1.SmartFake
    implements _i4.PlaybackSummary {
  _FakePlaybackSummary_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SignageApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignageApiClient extends _i1.Mock implements _i5.SignageApiClient {
  MockSignageApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  String get deviceId =>
      (super.noSuchMethod(
            Invocation.getter(#deviceId),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#deviceId),
            ),
          )
          as String);

  @override
  _i7.Future<_i8.VideoList?> syncPlaylist({int? lastSyncVersion}) =>
      (super.noSuchMethod(
            Invocation.method(#syncPlaylist, [], {
              #lastSyncVersion: lastSyncVersion,
            }),
            returnValue: _i7.Future<_i8.VideoList?>.value(),
          )
          as _i7.Future<_i8.VideoList?>);

  @override
  _i7.Future<_i2.PlaybackStatus> sendControlCommand({
    required String? command,
    Map<String, dynamic>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendControlCommand, [], {
              #command: command,
              #parameters: parameters,
            }),
            returnValue: _i7.Future<_i2.PlaybackStatus>.value(
              _FakePlaybackStatus_0(
                this,
                Invocation.method(#sendControlCommand, [], {
                  #command: command,
                  #parameters: parameters,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.PlaybackStatus>);

  @override
  _i7.Future<void> reportStatus({required _i2.PlaybackStatus? currentState}) =>
      (super.noSuchMethod(
            Invocation.method(#reportStatus, [], {#currentState: currentState}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> uploadHistory({
    required List<_i4.PlaybackHistoryEntry>? entries,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadHistory, [], {#entries: entries}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<Map<String, dynamic>> getServerInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getServerInfo, []),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> getVideoMetadata({
    required String? videoId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getVideoMetadata, [], {#videoId: videoId}),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<void> reportError({
    required String? errorType,
    required String? errorMessage,
    String? videoId,
    String? playlistId,
    Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reportError, [], {
              #errorType: errorType,
              #errorMessage: errorMessage,
              #videoId: videoId,
              #playlistId: playlistId,
              #context: context,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PlaylistDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaylistDatabase extends _i1.Mock implements _i9.PlaylistDatabase {
  MockPlaylistDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i3.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i7.Future<_i3.Database>.value(
              _FakeDatabase_1(this, Invocation.getter(#database)),
            ),
          )
          as _i7.Future<_i3.Database>);

  @override
  _i7.Future<void> upsertPlaylist(_i8.VideoList? playlist) =>
      (super.noSuchMethod(
            Invocation.method(#upsertPlaylist, [playlist]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i8.VideoList?> getPlaylist(String? playlistId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylist, [playlistId]),
            returnValue: _i7.Future<_i8.VideoList?>.value(),
          )
          as _i7.Future<_i8.VideoList?>);

  @override
  _i7.Future<List<_i8.VideoList>> getAllPlaylists({bool? activeOnly = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllPlaylists, [], {#activeOnly: activeOnly}),
            returnValue: _i7.Future<List<_i8.VideoList>>.value(
              <_i8.VideoList>[],
            ),
          )
          as _i7.Future<List<_i8.VideoList>>);

  @override
  _i7.Future<bool> deletePlaylist(String? playlistId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlaylist, [playlistId]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<String?> insertHistory(_i4.PlaybackHistoryEntry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#insertHistory, [entry]),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<bool> updateHistory(
    String? entryId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateHistory, [entryId, updates]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<List<_i4.PlaybackHistoryEntry>> queryHistory({
    DateTime? startDate,
    DateTime? endDate,
    String? videoId,
    String? playlistId,
    int? offset = 0,
    int? limit = 50,
    String? orderBy = 'started_at DESC',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#queryHistory, [], {
              #startDate: startDate,
              #endDate: endDate,
              #videoId: videoId,
              #playlistId: playlistId,
              #offset: offset,
              #limit: limit,
              #orderBy: orderBy,
            }),
            returnValue: _i7.Future<List<_i4.PlaybackHistoryEntry>>.value(
              <_i4.PlaybackHistoryEntry>[],
            ),
          )
          as _i7.Future<List<_i4.PlaybackHistoryEntry>>);

  @override
  _i7.Future<int> countHistory({
    DateTime? startDate,
    DateTime? endDate,
    String? videoId,
    String? playlistId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#countHistory, [], {
              #startDate: startDate,
              #endDate: endDate,
              #videoId: videoId,
              #playlistId: playlistId,
            }),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<_i4.PlaybackSummary> getPlaybackSummary({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaybackSummary, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i7.Future<_i4.PlaybackSummary>.value(
              _FakePlaybackSummary_2(
                this,
                Invocation.method(#getPlaybackSummary, [], {
                  #startDate: startDate,
                  #endDate: endDate,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.PlaybackSummary>);

  @override
  _i7.Future<int> cleanupOldHistory({int? retentionDays = 90}) =>
      (super.noSuchMethod(
            Invocation.method(#cleanupOldHistory, [], {
              #retentionDays: retentionDays,
            }),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
