// Mocks generated by Mockito 5.4.6 from annotations
// in signage_simple_player/test/screens/signage_player_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:signage_simple_player/api/signage_api_client.dart' as _i9;
import 'package:signage_simple_player/models/playback_history.dart' as _i11;
import 'package:signage_simple_player/models/playback_models.dart' as _i2;
import 'package:signage_simple_player/models/video_list.dart' as _i4;
import 'package:signage_simple_player/services/discovery_service.dart' as _i7;
import 'package:signage_simple_player/services/history_tracking_service.dart'
    as _i8;
import 'package:signage_simple_player/services/player_engine.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaybackStatus_1 extends _i1.SmartFake
    implements _i2.PlaybackStatus {
  _FakePlaybackStatus_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SignagePlayerEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignagePlayerEngine extends _i1.Mock
    implements _i3.SignagePlayerEngine {
  MockSignagePlayerEngine() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get preloadCount =>
      (super.noSuchMethod(Invocation.getter(#preloadCount), returnValue: 0)
          as int);

  @override
  int get currentIndex =>
      (super.noSuchMethod(Invocation.getter(#currentIndex), returnValue: 0)
          as int);

  @override
  _i2.PlaybackState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i2.PlaybackState.stopped,
          )
          as _i2.PlaybackState);

  @override
  _i4.LoopMode get loopMode =>
      (super.noSuchMethod(
            Invocation.getter(#loopMode),
            returnValue: _i4.LoopMode.continuous,
          )
          as _i4.LoopMode);

  @override
  Duration get currentPosition =>
      (super.noSuchMethod(
            Invocation.getter(#currentPosition),
            returnValue: _FakeDuration_0(
              this,
              Invocation.getter(#currentPosition),
            ),
          )
          as Duration);

  @override
  Duration get currentDuration =>
      (super.noSuchMethod(
            Invocation.getter(#currentDuration),
            returnValue: _FakeDuration_0(
              this,
              Invocation.getter(#currentDuration),
            ),
          )
          as Duration);

  @override
  double get progressPercent =>
      (super.noSuchMethod(Invocation.getter(#progressPercent), returnValue: 0.0)
          as double);

  @override
  bool get isPlaying =>
      (super.noSuchMethod(Invocation.getter(#isPlaying), returnValue: false)
          as bool);

  @override
  bool get isPaused =>
      (super.noSuchMethod(Invocation.getter(#isPaused), returnValue: false)
          as bool);

  @override
  bool get isStopped =>
      (super.noSuchMethod(Invocation.getter(#isStopped), returnValue: false)
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasError =>
      (super.noSuchMethod(Invocation.getter(#hasError), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<bool> loadPlaylist(String? playlistId) =>
      (super.noSuchMethod(
            Invocation.method(#loadPlaylist, [playlistId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> play() =>
      (super.noSuchMethod(
            Invocation.method(#play, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> resume() =>
      (super.noSuchMethod(
            Invocation.method(#resume, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> next() =>
      (super.noSuchMethod(
            Invocation.method(#next, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> previous() =>
      (super.noSuchMethod(
            Invocation.method(#previous, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> seekTo(Duration? position) =>
      (super.noSuchMethod(
            Invocation.method(#seekTo, [position]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void setLoopMode(_i4.LoopMode? mode) => super.noSuchMethod(
    Invocation.method(#setLoopMode, [mode]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i2.PlaybackStatus getPlaybackStatus(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaybackStatus, [deviceId]),
            returnValue: _FakePlaybackStatus_1(
              this,
              Invocation.method(#getPlaybackStatus, [deviceId]),
            ),
          )
          as _i2.PlaybackStatus);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SignageDiscoveryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignageDiscoveryService extends _i1.Mock
    implements _i7.SignageDiscoveryService {
  MockSignageDiscoveryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isRegistered =>
      (super.noSuchMethod(Invocation.getter(#isRegistered), returnValue: false)
          as bool);

  @override
  _i5.Future<bool> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> register() =>
      (super.noSuchMethod(
            Invocation.method(#register, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> sendHeartbeat() =>
      (super.noSuchMethod(
            Invocation.method(#sendHeartbeat, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deregister() =>
      (super.noSuchMethod(
            Invocation.method(#deregister, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [HistoryTrackingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryTrackingService extends _i1.Mock
    implements _i8.HistoryTrackingService {
  MockHistoryTrackingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isTracking =>
      (super.noSuchMethod(Invocation.getter(#isTracking), returnValue: false)
          as bool);

  @override
  void startTracking() => super.noSuchMethod(
    Invocation.method(#startTracking, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> stopTracking() =>
      (super.noSuchMethod(
            Invocation.method(#stopTracking, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> recordError(String? errorMessage) =>
      (super.noSuchMethod(
            Invocation.method(#recordError, [errorMessage]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> getStatistics({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getStatistics, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [SignageApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignageApiClient extends _i1.Mock implements _i9.SignageApiClient {
  MockSignageApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  String get deviceId =>
      (super.noSuchMethod(
            Invocation.getter(#deviceId),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#deviceId),
            ),
          )
          as String);

  @override
  _i5.Future<_i4.VideoList?> syncPlaylist({int? lastSyncVersion}) =>
      (super.noSuchMethod(
            Invocation.method(#syncPlaylist, [], {
              #lastSyncVersion: lastSyncVersion,
            }),
            returnValue: _i5.Future<_i4.VideoList?>.value(),
          )
          as _i5.Future<_i4.VideoList?>);

  @override
  _i5.Future<_i2.PlaybackStatus> sendControlCommand({
    required String? command,
    Map<String, dynamic>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendControlCommand, [], {
              #command: command,
              #parameters: parameters,
            }),
            returnValue: _i5.Future<_i2.PlaybackStatus>.value(
              _FakePlaybackStatus_1(
                this,
                Invocation.method(#sendControlCommand, [], {
                  #command: command,
                  #parameters: parameters,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.PlaybackStatus>);

  @override
  _i5.Future<void> reportStatus({required _i2.PlaybackStatus? currentState}) =>
      (super.noSuchMethod(
            Invocation.method(#reportStatus, [], {#currentState: currentState}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> uploadHistory({
    required List<_i11.PlaybackHistoryEntry>? entries,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadHistory, [], {#entries: entries}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<Map<String, dynamic>> getServerInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getServerInfo, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> getVideoMetadata({
    required String? videoId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getVideoMetadata, [], {#videoId: videoId}),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> reportError({
    required String? errorType,
    required String? errorMessage,
    String? videoId,
    String? playlistId,
    Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reportError, [], {
              #errorType: errorType,
              #errorMessage: errorMessage,
              #videoId: videoId,
              #playlistId: playlistId,
              #context: context,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
