#!/bin/bash
# generate-dev-secrets.sh
# Generates fresh development secrets and writes them to the project .env file.
# Run this script every time you want a new set of dev credentials.
#
# Usage:
#   ./scripts/generate-dev-secrets.sh          # writes to ../.env
#   ./scripts/generate-dev-secrets.sh --print  # prints only, does not write
#   ./scripts/generate-dev-secrets.sh --json   # outputs key=value pairs as JSON

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_ROOT/.env"

# ---------------------------------------------------------------------------
# 1) Strong random password (64 characters, alphanumeric + symbols)
# ---------------------------------------------------------------------------
generate_password() {
    # macOS / BSD-compatible: use openssl if available, fall back to /dev/urandom
    if command -v openssl &>/dev/null; then
        openssl rand -base64 48 | tr -d '\n/+=' | head -c 64
    else
        LC_ALL=C tr -dc 'A-Za-z0-9!@#$%^&*()_+-=[]{}|;:,.<>?' < /dev/urandom | head -c 64
    fi
}

# ---------------------------------------------------------------------------
# 2) UUID v4 token (uses macOS built-in uuidgen)
# ---------------------------------------------------------------------------
generate_uuid() {
    uuidgen
}

# ---------------------------------------------------------------------------
# 3) Another UUID for INTERNAL_SERVICE_TOKEN
# ---------------------------------------------------------------------------
generate_token() {
    uuidgen
}

# ---------------------------------------------------------------------------
# Generate all secrets
# ---------------------------------------------------------------------------
PASSWORD="$(generate_password)"
SECRET_KEY="$(generate_uuid)"
SERVICE_TOKEN="$(generate_token)"

# Ensure we always produce values
if [ -z "$PASSWORD" ] || [ -z "$SECRET_KEY" ] || [ -z "$SERVICE_TOKEN" ]; then
    echo "ERROR: Failed to generate one or more secrets." >&2
    exit 1
fi

case "${1:-}" in
    --print)
        echo "DEV_BOOTSTRAP_PASSWORD=$PASSWORD"
        echo "INTERNAL_SERVICE_TOKEN=$SERVICE_TOKEN"
        echo "SECRET_KEY=$SECRET_KEY"
        echo ""
        echo "# Add these to your shell or $ENV_FILE"
        echo "export ENVIRONMENT=development"
        echo "export DEV_BOOTSTRAP_PASSWORD=$PASSWORD"
        echo "export INTERNAL_SERVICE_TOKEN=$SERVICE_TOKEN"
        echo "export SECRET_KEY=$SECRET_KEY"
        ;;
    --json)
        echo "{"
        echo "  \"ENVIRONMENT\": \"development\","
        echo "  \"DEV_BOOTSTRAP_PASSWORD\": \"$PASSWORD\","
        echo "  \"INTERNAL_SERVICE_TOKEN\": \"$SERVICE_TOKEN\","
        echo "  \"SECRET_KEY\": \"$SECRET_KEY\""
        echo "}"
        ;;
    *)
        # Write to .env file
        cat > "$ENV_FILE" <<EOF
# PPL Meta Platform — Development Secrets
# Auto-generated by scripts/generate-dev-secrets.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Regenerate anytime with: ./scripts/generate-dev-secrets.sh

ENVIRONMENT=development
DEV_BOOTSTRAP_PASSWORD=$PASSWORD
INTERNAL_SERVICE_TOKEN=$SERVICE_TOKEN
SECRET_KEY=$SECRET_KEY
EOF

        echo "✅ Secrets written to $ENV_FILE"
        echo ""
        echo "   DEV_BOOTSTRAP_PASSWORD : $PASSWORD"
        echo "   INTERNAL_SERVICE_TOKEN : $SERVICE_TOKEN"
        echo "   SECRET_KEY             : $SECRET_KEY"
        echo ""
        echo "To load into your current shell:"
        echo "   export ENVIRONMENT=development"
        echo "   export DEV_BOOTSTRAP_PASSWORD=$PASSWORD"
        echo "   export INTERNAL_SERVICE_TOKEN=$SERVICE_TOKEN"
        echo "   export SECRET_KEY=$SECRET_KEY"
        ;;
esac