#!/usr/bin/env bash
# Write deployment/windows-installer/release-manifest.yml from GHCR digests.
#
# After Stage 2 (full, selective, or retag-forward), run:
#   RELEASE_TAG=2.25.82 ./scripts/write_release_manifest.sh
#
# Options:
#   --allow-partial   write even if some images are missing (digests empty / omitted)
#   --outfile PATH    override output path
#
# Commit the updated manifest in a follow-up Stage 1 (coherence artifact in git).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=platform_release_images.sh
source "$ROOT/scripts/platform_release_images.sh"

ALLOW_PARTIAL=0
OUTFILE=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --allow-partial) ALLOW_PARTIAL=1; shift ;;
    --outfile) OUTFILE="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,14p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown arg: $1" >&2
      exit 2
      ;;
  esac
done

REGISTRY="${REGISTRY:-$PLATFORM_REGISTRY_DEFAULT}"
RELEASE_TAG="${RELEASE_TAG:-$(tr -d '[:space:]' < "$ROOT/VERSION")}"
GIT_SHA="$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)"
CREATED_AT="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
OUTFILE="${OUTFILE:-$ROOT/deployment/windows-installer/release-manifest.yml}"

echo "Resolving digests for platform_version=${RELEASE_TAG} at ${REGISTRY}"
echo

missing=0
declare -a DIGESTS=()
declare -a TAGS=()

for image in "${PLATFORM_IMAGE_NAMES[@]}"; do
  ref="$(platform_image_ref "$REGISTRY" "$image" "$RELEASE_TAG")"
  if digest="$(platform_resolve_digest "$ref")"; then
    echo "OK      ${ref}  ${digest}"
    DIGESTS+=("$digest")
    TAGS+=("$RELEASE_TAG")
  else
    echo "MISSING ${ref}"
    DIGESTS+=("")
    TAGS+=("$RELEASE_TAG")
    missing=$((missing + 1))
  fi
done

echo
if (( missing > 0 )) && [[ "$ALLOW_PARTIAL" -ne 1 ]]; then
  echo "FAILED: ${missing} image(s) missing digests for ${RELEASE_TAG}" >&2
  echo "Finish Stage 2 (rebuild or retag-forward), or pass --allow-partial." >&2
  exit 1
fi

mkdir -p "$(dirname "$OUTFILE")"
{
  cat <<EOF
# EyeNet platform release manifest (v1)
# Generated by scripts/write_release_manifest.sh — do not hand-edit digests.
# Installers still pull by tag (:platform_version) today; digests are the
# coherence / audit layer (Mode D). Digest-pinned compose is a later step.
schema_version: 1
platform_version: "${RELEASE_TAG}"
git_sha: "${GIT_SHA}"
created_at: "${CREATED_AT}"
registry: "${REGISTRY}"
images:
EOF
  i=0
  for image in "${PLATFORM_IMAGE_NAMES[@]}"; do
    digest="${DIGESTS[$i]}"
    tag="${TAGS[$i]}"
    echo "  ${image}:"
    echo "    tag: \"${tag}\""
    if [[ -n "$digest" ]]; then
      echo "    digest: \"${digest}\""
    else
      echo "    digest: null  # missing at write time"
    fi
    i=$((i + 1))
  done
} >"$OUTFILE"

echo "Wrote ${OUTFILE}"
echo "Next: ./scripts/verify_release_manifest.sh && Stage 1 commit of release-manifest.yml"
