// Mocks generated by Mockito 5.4.6 from annotations
// in signage_simple_player/test/history_tracking_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:signage_simple_player/database/playlist_database.dart' as _i5;
import 'package:signage_simple_player/models/playback_history.dart' as _i3;
import 'package:signage_simple_player/models/playback_models.dart' as _i4;
import 'package:signage_simple_player/models/video_list.dart' as _i7;
import 'package:signage_simple_player/services/player_engine.dart' as _i8;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaybackSummary_1 extends _i1.SmartFake
    implements _i3.PlaybackSummary {
  _FakePlaybackSummary_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_2 extends _i1.SmartFake implements Duration {
  _FakeDuration_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaybackStatus_3 extends _i1.SmartFake
    implements _i4.PlaybackStatus {
  _FakePlaybackStatus_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PlaylistDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaylistDatabase extends _i1.Mock implements _i5.PlaylistDatabase {
  MockPlaylistDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i6.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i6.Future<_i2.Database>);

  @override
  _i6.Future<void> upsertPlaylist(_i7.VideoList? playlist) =>
      (super.noSuchMethod(
            Invocation.method(#upsertPlaylist, [playlist]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i7.VideoList?> getPlaylist(String? playlistId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylist, [playlistId]),
            returnValue: _i6.Future<_i7.VideoList?>.value(),
          )
          as _i6.Future<_i7.VideoList?>);

  @override
  _i6.Future<List<_i7.VideoList>> getAllPlaylists({bool? activeOnly = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllPlaylists, [], {#activeOnly: activeOnly}),
            returnValue: _i6.Future<List<_i7.VideoList>>.value(
              <_i7.VideoList>[],
            ),
          )
          as _i6.Future<List<_i7.VideoList>>);

  @override
  _i6.Future<bool> deletePlaylist(String? playlistId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlaylist, [playlistId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<String?> insertHistory(_i3.PlaybackHistoryEntry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#insertHistory, [entry]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<bool> updateHistory(
    String? entryId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateHistory, [entryId, updates]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<List<_i3.PlaybackHistoryEntry>> queryHistory({
    DateTime? startDate,
    DateTime? endDate,
    String? videoId,
    String? playlistId,
    int? offset = 0,
    int? limit = 50,
    String? orderBy = 'started_at DESC',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#queryHistory, [], {
              #startDate: startDate,
              #endDate: endDate,
              #videoId: videoId,
              #playlistId: playlistId,
              #offset: offset,
              #limit: limit,
              #orderBy: orderBy,
            }),
            returnValue: _i6.Future<List<_i3.PlaybackHistoryEntry>>.value(
              <_i3.PlaybackHistoryEntry>[],
            ),
          )
          as _i6.Future<List<_i3.PlaybackHistoryEntry>>);

  @override
  _i6.Future<int> countHistory({
    DateTime? startDate,
    DateTime? endDate,
    String? videoId,
    String? playlistId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#countHistory, [], {
              #startDate: startDate,
              #endDate: endDate,
              #videoId: videoId,
              #playlistId: playlistId,
            }),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<_i3.PlaybackSummary> getPlaybackSummary({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaybackSummary, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i6.Future<_i3.PlaybackSummary>.value(
              _FakePlaybackSummary_1(
                this,
                Invocation.method(#getPlaybackSummary, [], {
                  #startDate: startDate,
                  #endDate: endDate,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.PlaybackSummary>);

  @override
  _i6.Future<int> cleanupOldHistory({int? retentionDays = 90}) =>
      (super.noSuchMethod(
            Invocation.method(#cleanupOldHistory, [], {
              #retentionDays: retentionDays,
            }),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [SignagePlayerEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignagePlayerEngine extends _i1.Mock
    implements _i8.SignagePlayerEngine {
  MockSignagePlayerEngine() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get preloadCount =>
      (super.noSuchMethod(Invocation.getter(#preloadCount), returnValue: 0)
          as int);

  @override
  int get currentIndex =>
      (super.noSuchMethod(Invocation.getter(#currentIndex), returnValue: 0)
          as int);

  @override
  _i4.PlaybackState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i4.PlaybackState.stopped,
          )
          as _i4.PlaybackState);

  @override
  _i7.LoopMode get loopMode =>
      (super.noSuchMethod(
            Invocation.getter(#loopMode),
            returnValue: _i7.LoopMode.continuous,
          )
          as _i7.LoopMode);

  @override
  Duration get currentPosition =>
      (super.noSuchMethod(
            Invocation.getter(#currentPosition),
            returnValue: _FakeDuration_2(
              this,
              Invocation.getter(#currentPosition),
            ),
          )
          as Duration);

  @override
  Duration get currentDuration =>
      (super.noSuchMethod(
            Invocation.getter(#currentDuration),
            returnValue: _FakeDuration_2(
              this,
              Invocation.getter(#currentDuration),
            ),
          )
          as Duration);

  @override
  double get progressPercent =>
      (super.noSuchMethod(Invocation.getter(#progressPercent), returnValue: 0.0)
          as double);

  @override
  bool get isPlaying =>
      (super.noSuchMethod(Invocation.getter(#isPlaying), returnValue: false)
          as bool);

  @override
  bool get isPaused =>
      (super.noSuchMethod(Invocation.getter(#isPaused), returnValue: false)
          as bool);

  @override
  bool get isStopped =>
      (super.noSuchMethod(Invocation.getter(#isStopped), returnValue: false)
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasError =>
      (super.noSuchMethod(Invocation.getter(#hasError), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<bool> loadPlaylist(String? playlistId) =>
      (super.noSuchMethod(
            Invocation.method(#loadPlaylist, [playlistId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> play() =>
      (super.noSuchMethod(
            Invocation.method(#play, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> resume() =>
      (super.noSuchMethod(
            Invocation.method(#resume, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> next() =>
      (super.noSuchMethod(
            Invocation.method(#next, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> previous() =>
      (super.noSuchMethod(
            Invocation.method(#previous, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> seekTo(Duration? position) =>
      (super.noSuchMethod(
            Invocation.method(#seekTo, [position]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void setLoopMode(_i7.LoopMode? mode) => super.noSuchMethod(
    Invocation.method(#setLoopMode, [mode]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.PlaybackStatus getPlaybackStatus(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaybackStatus, [deviceId]),
            returnValue: _FakePlaybackStatus_3(
              this,
              Invocation.method(#getPlaybackStatus, [deviceId]),
            ),
          )
          as _i4.PlaybackStatus);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
