// Mocks generated by Mockito 5.4.6 from annotations
// in signage_simple_player/test/player_engine_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:signage_simple_player/database/playlist_database.dart' as _i4;
import 'package:signage_simple_player/models/playback_history.dart' as _i3;
import 'package:signage_simple_player/models/video_list.dart' as _i6;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaybackSummary_1 extends _i1.SmartFake
    implements _i3.PlaybackSummary {
  _FakePlaybackSummary_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PlaylistDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaylistDatabase extends _i1.Mock implements _i4.PlaylistDatabase {
  MockPlaylistDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i5.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i5.Future<_i2.Database>);

  @override
  _i5.Future<void> upsertPlaylist(_i6.VideoList? playlist) =>
      (super.noSuchMethod(
            Invocation.method(#upsertPlaylist, [playlist]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i6.VideoList?> getPlaylist(String? playlistId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylist, [playlistId]),
            returnValue: _i5.Future<_i6.VideoList?>.value(),
          )
          as _i5.Future<_i6.VideoList?>);

  @override
  _i5.Future<List<_i6.VideoList>> getAllPlaylists({bool? activeOnly = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllPlaylists, [], {#activeOnly: activeOnly}),
            returnValue: _i5.Future<List<_i6.VideoList>>.value(
              <_i6.VideoList>[],
            ),
          )
          as _i5.Future<List<_i6.VideoList>>);

  @override
  _i5.Future<bool> deletePlaylist(String? playlistId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlaylist, [playlistId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<String?> insertHistory(_i3.PlaybackHistoryEntry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#insertHistory, [entry]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<bool> updateHistory(
    String? entryId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateHistory, [entryId, updates]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<_i3.PlaybackHistoryEntry>> queryHistory({
    DateTime? startDate,
    DateTime? endDate,
    String? videoId,
    String? playlistId,
    int? offset = 0,
    int? limit = 50,
    String? orderBy = 'started_at DESC',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#queryHistory, [], {
              #startDate: startDate,
              #endDate: endDate,
              #videoId: videoId,
              #playlistId: playlistId,
              #offset: offset,
              #limit: limit,
              #orderBy: orderBy,
            }),
            returnValue: _i5.Future<List<_i3.PlaybackHistoryEntry>>.value(
              <_i3.PlaybackHistoryEntry>[],
            ),
          )
          as _i5.Future<List<_i3.PlaybackHistoryEntry>>);

  @override
  _i5.Future<int> countHistory({
    DateTime? startDate,
    DateTime? endDate,
    String? videoId,
    String? playlistId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#countHistory, [], {
              #startDate: startDate,
              #endDate: endDate,
              #videoId: videoId,
              #playlistId: playlistId,
            }),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<_i3.PlaybackSummary> getPlaybackSummary({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaybackSummary, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i5.Future<_i3.PlaybackSummary>.value(
              _FakePlaybackSummary_1(
                this,
                Invocation.method(#getPlaybackSummary, [], {
                  #startDate: startDate,
                  #endDate: endDate,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.PlaybackSummary>);

  @override
  _i5.Future<int> cleanupOldHistory({int? retentionDays = 90}) =>
      (super.noSuchMethod(
            Invocation.method(#cleanupOldHistory, [], {
              #retentionDays: retentionDays,
            }),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
